# Every field added here must also be added to the expandProps map in
# build-logic/src/main/groovy/multiloader-common.gradle

# Project
version=1.1.0
group=net.dakes.cornerlink
java_version=25

# Common
minecraft_version=26.2
mod_name=Portal Cornerlink
mod_author=Dakes
mod_id=dakes_cornerlink
license=LGPL-2.1-only
credits=Fork of Corner Portal Linking by starbidou
description=Use glazed terracotta to help link Nether portals.
minecraft_version_range=[26.1,27)
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric, see https://fabricmc.net/develop/
fabric_version=0.158.0+26.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.64
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
